import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import esbuild from 'esbuild';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const watch = process.argv.includes('--watch');

/**
 * The Terminalogue Marp engine, vendored rather than depended on.
 *
 * It is the bundle `@terminalogue/marp` builds, copied into `vendor/` from the
 * Terminalogue repository. Vendoring keeps this plugin buildable on its own,
 * with no npm dependency and no network: what is in `vendor/` is exactly what
 * ships, and it is readable JavaScript rather than something fetched at build
 * time. Refresh it with `node scripts/vendor-engine.mjs <path-to-Terminalogue>`.
 */
const ENGINE = resolve(root, 'vendor/terminalogue-marp-engine.mjs');

/**
 * Embeds the self-contained Terminalogue Marp engine into the plugin.
 *
 * An Obsidian plugin is `main.js`, `manifest.json` and nothing the reader has
 * to install, so the engine travels as a string and is written into a scratch
 * directory when a presentation is generated. It is the same bundle
 * `@terminalogue/marp` ships, which is the same parser, renderer and stylesheet
 * VS Code and Obsidian use — with no `node_modules` and no network needed
 * anywhere near the generated HTML.
 */
function embedEngine() {
  const source = readFileSync(ENGINE, 'utf8');
  const to = resolve(root, 'src/generated/engine-source.ts');

  mkdirSync(dirname(to), { recursive: true });
  writeFileSync(
    to,
    `/*
 * Generated by scripts/build.mjs. Do not edit.
 *
 * The bundled @terminalogue/marp engine, written into a scratch directory and
 * passed to Marp CLI with --engine.
 */

/** A self-contained ES module: no imports, no network, no node_modules. */
export const TERMINALOGUE_MARP_ENGINE: string = ${JSON.stringify(source)};
`,
    'utf8',
  );
  console.log(`[terminalogue-presenter] engine -> ${to} (${source.length} B)`);
}

/** @type {import('esbuild').BuildOptions[]} */
const builds = [
  {
    entryPoints: [resolve(root, 'src/main.ts')],
    outfile: resolve(root, 'main.js'),
    format: 'cjs',
    platform: 'node',
    target: 'es2020',
  },
  {
    // The pure logic, exposed as CommonJS so the unit tests can reach it
    // without an Obsidian window: argument building, executable lookup, the
    // process lifecycle and the scratch directory.
    entryPoints: [resolve(root, 'src/internals.ts')],
    outfile: resolve(root, 'dist/internals.cjs'),
    format: 'cjs',
    platform: 'node',
    target: 'es2020',
  },
];

const common = {
  bundle: true,
  sourcemap: watch ? 'inline' : false,
  minify: !watch,
  logLevel: 'info',
  // Provided by the Obsidian runtime, never bundled.
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    'node:*',
  ],
};

embedEngine();

if (watch) {
  const contexts = await Promise.all(
    builds.map((build) => esbuild.context({ ...common, ...build })),
  );
  await Promise.all(contexts.map((context) => context.watch()));
  console.log('[terminalogue-presenter] watching');
} else {
  await Promise.all(builds.map((build) => esbuild.build({ ...common, ...build })));
}
